# Generated by Django 3.0.8 on 2020-08-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.Pet')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Walker')),
            ],
        ),
    ]
