# Generated by Django 3.0.8 on 2020-07-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(max_length=50, verbose_name='Personality Type')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Species Name')),
                ('is_exotic', models.BooleanField(default=False, verbose_name='Exotic')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('picture', models.ImageField(height_field=200, upload_to='avatars', verbose_name='Picture', width_field=200)),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('adopted', models.BooleanField(default=False, verbose_name='Adopted')),
                ('adopted_date', models.DateField(verbose_name='Adopted Date')),
                ('personality_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HelpingPawWeb.Personality')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HelpingPawWeb.Species')),
            ],
        ),
    ]
