# Generated by Django 3.0.8 on 2020-07-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='species',
            name='is_exotic',
        ),
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Years Old'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacity')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HelpingPawWeb.City')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('contribution', models.CharField(max_length=5000, verbose_name='Contribution')),
                ('shelter_contributed_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HelpingPawWeb.Shelter')),
            ],
        ),
    ]
