# Generated by Django 3.0.8 on 2020-07-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0003_species_is_exotic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
