# Generated by Django 3.0.8 on 2020-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0004_auto_20200730_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='description',
            field=models.CharField(default='-', max_length=5000),
            preserve_default=False,
        ),
    ]
