# Generated by Django 3.0.8 on 2020-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0005_personality_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adopted_date',
            field=models.DateField(blank=True, verbose_name='Adopted Date'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(upload_to='avatars', verbose_name='Picture'),
        ),
    ]
