# Generated by Django 3.0.8 on 2020-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0006_auto_20200730_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adopted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Adopted Date'),
        ),
    ]
