# Generated by Django 3.0.8 on 2020-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0007_auto_20200730_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='picture',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='picture',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Picture'),
        ),
    ]
