# Generated by Django 3.0.8 on 2020-08-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0008_auto_20200801_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Reserved'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('reserved_date', models.DateTimeField(verbose_name='Reservation Date')),
                ('reserved_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpingPawWeb.Animal')),
                ('reserved_shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpingPawWeb.Shelter')),
            ],
        ),
    ]
