# Generated by Django 3.0.8 on 2020-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0009_auto_20200801_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='vlad.almasan@accesa.eu', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
