# Generated by Django 3.0.8 on 2020-08-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0010_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='HelpingPawWeb.Shelter'),
            preserve_default=False,
        ),
    ]
