# Generated by Django 3.0.8 on 2020-08-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingPawWeb', '0011_animal_shelter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='personality',
            options={'verbose_name_plural': 'Personalities'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
