# Generated by Django 3.0.8 on 2020-08-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_calculator', '0002_auto_20200803_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='add_date',
            field=models.DateField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='update_date',
            field=models.DateField(verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='add_date',
            field=models.DateField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='update_date',
            field=models.DateField(verbose_name='date updated'),
        ),
    ]
