# Generated by Django 3.0.8 on 2020-08-05 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_calculator', '0007_auto_20200804_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_Type',
            new_name='IngredientType',
        ),
        migrations.RenameModel(
            old_name='Recipe_Type',
            new_name='RecipeType',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='update_date',
        ),
        migrations.AddField(
            model_name='cost',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity (g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='update_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Update Date & Time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='update_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Update Date & Time'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
