# Generated by Django 3.0.8 on 2020-08-05 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_calculator', '0008_auto_20200805_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date & Time'),
        ),
    ]
