# Generated by Django 3.0.8 on 2020-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_drug', models.CharField(max_length=200)),
                ('data_of_expiration', models.DateTimeField(verbose_name='date expiration')),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pacient', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('renew_recipe', models.DateTimeField(verbose_name='renew data')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
