# Generated by Django 3.0.8 on 2020-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0002_auto_20200726_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='renew_recipe',
        ),
        migrations.AddField(
            model_name='drugs',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pacient',
            name='email_address',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='data_of_expiration',
            field=models.DateField(),
        ),
    ]
