# Generated by Django 3.0.8 on 2020-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0003_auto_20200727_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='data_of_expiration',
            field=models.DateField(blank=True),
        ),
    ]
