# Generated by Django 3.0.8 on 2020-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0004_auto_20200728_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='data_of_expiration',
            field=models.DateField(),
        ),
    ]
