# Generated by Django 3.0.8 on 2020-08-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0006_auto_20200729_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_renew', models.DateTimeField(verbose_name='date_of_renew')),
                ('drug_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm_tree.Drugs')),
                ('email_address_pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm_tree.Pacient')),
            ],
        ),
    ]
