# Generated by Django 3.0.8 on 2020-08-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0007_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='drug_used',
        ),
        migrations.AddField(
            model_name='recipe',
            name='drug_used',
            field=models.ManyToManyField(to='pharm_tree.Drugs'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='email_address_pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_tree.Pacient'),
        ),
    ]
