# Generated by Django 3.0.8 on 2020-08-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_tree', '0012_auto_20200802_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='drug_used',
            new_name='drugs',
        ),
    ]
