# Generated by Django 3.0.8 on 2020-08-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField(max_length=5)),
                ('Customer_Name', models.CharField(max_length=30)),
                ('first_order', models.DateField()),
                ('last_order', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity_available', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField(max_length=10)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField(max_length=3)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Customer')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Product')),
            ],
        ),
    ]
