# Generated by Django 3.0.8 on 2020-08-01 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField()),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Customer_ID',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Product'),
        ),
    ]
