# Generated by Django 3.0.8 on 2020-08-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20200801_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_code',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Orders.Customer'),
            preserve_default=False,
        ),
    ]
