# Generated by Django 3.0.8 on 2020-07-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='county',
            new_name='state',
        ),
    ]
