# Generated by Django 3.0.8 on 2020-08-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecunia', '0002_auto_20200731_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroverview',
            name='total_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='useroverview',
            name='total_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='useroverview',
            name='total_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='useroverview',
            name='total_transactions',
            field=models.FloatField(default=0.0),
        ),
    ]
