# Generated by Django 3.0.8 on 2020-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecunia', '0005_remove_transaction_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEP', 'Deposit'), ('WDW', 'Withdraw')], max_length=30),
        ),
    ]
