# Generated by Django 3.0.8 on 2020-08-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecunia', '0006_auto_20200803_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
