# Generated by Django 3.0.8 on 2020-08-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecunia', '0007_auto_20200803_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=30),
        ),
    ]
