# Generated by Django 3.0.8 on 2020-08-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item1', to='items.Item')),
                ('item_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item2', to='items.Item')),
                ('item_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item3', to='items.Item')),
                ('item_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item4', to='items.Item')),
                ('item_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item5', to='items.Item')),
                ('item_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item6', to='items.Item')),
                ('item_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item7', to='items.Item')),
                ('item_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item8', to='items.Item')),
            ],
        ),
    ]
