# Generated by Django 3.0.8 on 2020-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='item_8',
        ),
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(to='items.Item'),
        ),
    ]
