# Generated by Django 3.0.8 on 2020-08-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('recipes', '0003_auto_20200804_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='items',
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item1', to='items.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item2', to='items.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item3', to='items.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item4', to='items.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item5', to='items.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item6', to='items.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item7', to='items.Item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item8', to='items.Item'),
        ),
    ]
