# Generated by Django 3.0.8 on 2020-08-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('recipes', '0006_auto_20200805_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(null=True, to='items.Item'),
        ),
    ]
